name: Elgiganten bevakare

on:
  workflow_dispatch:

jobs:
  bevakare:
    runs-on: ubuntu-latest

    steps:
      - name: Hämta filer
        uses: actions/checkout@v4

      - name: Installera Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Kör bevakaren
        run: python bevakare.py
